import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0e131e',
        'surface-dim': '#0e131e',
        'surface-bright': '#343945',
        'surface-container-lowest': '#080e18',
        'surface-container-low': '#161c26',
        'surface-container': '#1a202a',
        'surface-container-high': '#242a35',
        'surface-container-highest': '#2f3540',
        'on-surface': '#dde2f1',
        'on-surface-variant': '#c0c6d6',
        'inverse-surface': '#dde2f1',
        'inverse-on-surface': '#2b313c',
        outline: '#8a919f',
        'outline-variant': '#404754',
        'surface-tint': '#a7c8ff',
        primary: '#a7c8ff',
        'on-primary': '#003061',
        'primary-container': '#3291ff',
        'on-primary-container': '#002a55',
        'inverse-primary': '#005eb2',
        secondary: '#8ee3ff',
        'on-secondary': '#003642',
        'secondary-container': '#00ccf5',
        'on-secondary-container': '#005264',
        tertiary: '#b9c8de',
        'on-tertiary': '#233143',
        'tertiary-container': '#8392a6',
        'on-tertiary-container': '#1c2b3c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a7c8ff',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#004788',
        'secondary-fixed': '#b3ebff',
        'secondary-fixed-dim': '#37d7ff',
        'on-secondary-fixed': '#001f27',
        'on-secondary-fixed-variant': '#004e5f',
        'tertiary-fixed': '#d4e4fa',
        'tertiary-fixed-dim': '#b9c8de',
        'on-tertiary-fixed': '#0d1c2d',
        'on-tertiary-fixed-variant': '#39485a',
        background: '#0e131e',
        'on-background': '#dde2f1',
        'surface-variant': '#2f3540',
      },
      fontFamily: {
        geist: ['var(--font-geist)', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-lg': '2.5rem',
        'margin': '1.5rem',
        'margin-md': '3rem',
        'margin-lg': '6rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        'space-3xl': '6rem',
      },
    },
  },
  plugins: [],
};
export default config;
